name: CI

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  nix-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix fmt -- --fail-on-change
